[BACKLOG-19949] Updating the sandbox in the VizAPI tutorial.
pentaho/pentaho-engineering-samples pull request #42
Opened 2017-11-28 16:46 UTC by dcleao

Depends on pentaho/pentaho-platform-plugin-common-ui#1213.

@pentaho/millenniumfalcon please review.

2017-11-28 16:48 UTC, wingman-pentaho commented
### Build Skipped

:white_check_mark: There was nothing to build. The changes are probably excluded by the build rules. If this is an error, please contact your system administrator.

2017-11-28 16:48 UTC, wingman-pentaho commented
### Build Failed

:x: Something went wrong while validating this pull request.

#### Build Commands

```sh
```

##### Stdout log
###### (last 100 lines)

```console
Config enriched: If no api token specified, use environment variable
Config enriched: If source control is github, set git binary path
Config enriched: Set the slackbot url
Config enriched: If github SourceControlType and null StatusUpdateType, use github
Config enriched: If github SourceControlType and StatusUpdaterType and null ApiToken, use the one from SourceRetriever
Config enriched: If github SourceControlType and StatusUpdaterType and null Organization, use the one from SourceRetriever
Config enriched: If github SourceControlType and StatusUpdaterType and null Repository, use the one from SourceRetriever
Config enriched: If github SourceControlType and StatusUpdaterType and null PullRequest, use the one from SourceRetriever
Config enriched: CheckstyleAnalyzer is enabled by default
Retrieving source with org.pentaho.build.buddy.bundles.source.github.SlackbotGithubSourceRetriever@609af454
VCS Commands:
clone: [git, clone, --depth=1, --branch, master, https://[GITHUB TOKEN]@github.com/pentaho/pentaho-engineering-samples.git, pentaho-engineering-samples-base-42-5b23c728-40c6-44dd-a5be-dbed1f56343c]
fetch: [git, fetch, --depth=2, origin, pull/42/head:pullRequest]
merge: [git, merge, --no-edit, --no-ff, -Xtheirs, -Xignore-space-change, pullRequest]
HEAD is now at d283a1b Merge pull request #37 from jonjarvis/BISERVER-13837
Merge made by the 'recursive' strategy.
 .../javascript-apis/platform/visual-samples-bar-d3/.npmignore       | 1 -
 .../javascript-apis/platform/visual-samples-bar-d3/sandbox.html     | 6 +++---
 2 files changed, 3 insertions(+), 4 deletions(-)
GithubSourceRetriever file list:
[modified]	Samples_for_Extending_Pentaho/javascript-apis/platform/visual-samples-bar-d3/.npmignore
[modified]	Samples_for_Extending_Pentaho/javascript-apis/platform/visual-samples-bar-d3/sandbox.html
BuildToolDetector unable to determine build type, falling back to config defaults
Build file exclusion pattern: (\A|/)(assembly|assemblies)/
```

#### Stderr log
###### (last 100 lines)

```console
Cloning into 'pentaho-engineering-samples-base-42-5b23c728-40c6-44dd-a5be-dbed1f56343c'...
From https://github.com/pentaho/pentaho-engineering-samples
 * [new ref]         refs/pull/42/head -> pullRequest
java.lang.Exception: java.lang.RuntimeException: org.eclipse.egit.github.core.client.RequestException: Not Found (404)
	at org.pentaho.build.buddy.bundles.orchestrator.OrchestratorImpl.orchestrate(OrchestratorImpl.java:387)
	at Proxydb7010ba_4c63_496c_a092_7bcd6ef97c89.orchestrate(Unknown Source)
	at org.pentaho.build.buddy.bundles.rest.OrchestratorRestService$1.write(OrchestratorRestService.java:62)
	at org.apache.cxf.jaxrs.provider.BinaryDataProvider.writeTo(BinaryDataProvider.java:172)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.writeMessageBody(JAXRSUtils.java:1381)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.serializeMessage(JAXRSOutInterceptor.java:244)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.processResponse(JAXRSOutInterceptor.java:120)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleMessage(JAXRSOutInterceptor.java:83)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.interceptor.OutgoingChainInterceptor.handleMessage(OutgoingChainInterceptor.java:83)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:253)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:287)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: org.eclipse.egit.github.core.client.RequestException: Not Found (404)
	at org.pentaho.build.buddy.bundles.source.github.GithubSourceRetriever.onStop(GithubSourceRetriever.java:280)
	at org.pentaho.build.buddy.bundles.source.github.SlackbotGithubSourceRetriever.onStop(SlackbotGithubSourceRetriever.java:36)
	at Proxy9d06b07d_ca2a_4133_adf6_83b92691d70e.onStop(Unknown Source)
	at org.pentaho.build.buddy.bundles.orchestrator.OrchestratorImpl.doNotBuild(OrchestratorImpl.java:516)
	at org.pentaho.build.buddy.bundles.orchestrator.OrchestratorImpl.orchestrate(OrchestratorImpl.java:354)
	... 41 more
Caused by: org.eclipse.egit.github.core.client.RequestException: Not Found (404)
	at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:552)
	at org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:643)
	at org.eclipse.egit.github.core.client.GitHubClient.post(GitHubClient.java:757)
	at org.pentaho.build.buddy.bundles.source.github.GithubCommitService$Delegate$1.post(GithubCommitService.java:50)
	at org.eclipse.egit.github.core.service.CommitService.createStatus(CommitService.java:426)
	at org.pentaho.build.buddy.bundles.source.github.GithubCommitService.createStatus(GithubCommitService.java:35)
	at org.pentaho.build.buddy.bundles.source.github.GithubSourceRetriever.onStop(GithubSourceRetriever.java:278)
	... 45 more

```

2017-11-28 17:32 UTC, nantunes requested changes

2017-11-28 17:32 UTC, nantunes commented on Samples_for_Extending_Pentaho/javascript-apis/platform/visual-samples-bar-d3/.npmignore
> -sample-data/*
Yep, João Gameiro noticed that today. But should be replaced with `sandbox-data.json`, not just deleted.

2017-11-28 18:07 UTC, wingman-pentaho commented
### Build Skipped

:white_check_mark: There was nothing to build. The changes are probably excluded by the build rules. If this is an error, please contact your system administrator.

2017-11-28 18:07 UTC, wingman-pentaho commented
### Build Failed

:x: Something went wrong while validating this pull request.

#### Build Commands

```sh
```

##### Stdout log
###### (last 100 lines)

```console
Config enriched: If no api token specified, use environment variable
Config enriched: If source control is github, set git binary path
Config enriched: Set the slackbot url
Config enriched: If github SourceControlType and null StatusUpdateType, use github
Config enriched: If github SourceControlType and StatusUpdaterType and null ApiToken, use the one from SourceRetriever
Config enriched: If github SourceControlType and StatusUpdaterType and null Organization, use the one from SourceRetriever
Config enriched: If github SourceControlType and StatusUpdaterType and null Repository, use the one from SourceRetriever
Config enriched: If github SourceControlType and StatusUpdaterType and null PullRequest, use the one from SourceRetriever
Config enriched: CheckstyleAnalyzer is enabled by default
Retrieving source with org.pentaho.build.buddy.bundles.source.github.SlackbotGithubSourceRetriever@609af454
VCS Commands:
clone: [git, clone, --depth=1, --branch, master, https://[GITHUB TOKEN]@github.com/pentaho/pentaho-engineering-samples.git, pentaho-engineering-samples-base-42-6edc5461-7e7a-439c-99ee-74da86227bfb]
fetch: [git, fetch, --depth=3, origin, pull/42/head:pullRequest]
merge: [git, merge, --no-edit, --no-ff, -Xtheirs, -Xignore-space-change, pullRequest]
HEAD is now at d283a1b Merge pull request #37 from jonjarvis/BISERVER-13837
Merge made by the 'recursive' strategy.
 .../javascript-apis/platform/visual-samples-bar-d3/.npmignore       | 2 +-
 .../javascript-apis/platform/visual-samples-bar-d3/sandbox.html     | 6 +++---
 2 files changed, 4 insertions(+), 4 deletions(-)
GithubSourceRetriever file list:
[modified]	Samples_for_Extending_Pentaho/javascript-apis/platform/visual-samples-bar-d3/.npmignore
[modified]	Samples_for_Extending_Pentaho/javascript-apis/platform/visual-samples-bar-d3/sandbox.html
BuildToolDetector unable to determine build type, falling back to config defaults
Build file exclusion pattern: (\A|/)(assembly|assemblies)/
```

#### Stderr log
###### (last 100 lines)

```console
Cloning into 'pentaho-engineering-samples-base-42-6edc5461-7e7a-439c-99ee-74da86227bfb'...
From https://github.com/pentaho/pentaho-engineering-samples
 * [new ref]         refs/pull/42/head -> pullRequest
java.lang.Exception: java.lang.RuntimeException: org.eclipse.egit.github.core.client.RequestException: Not Found (404)
	at org.pentaho.build.buddy.bundles.orchestrator.OrchestratorImpl.orchestrate(OrchestratorImpl.java:387)
	at Proxydb7010ba_4c63_496c_a092_7bcd6ef97c89.orchestrate(Unknown Source)
	at org.pentaho.build.buddy.bundles.rest.OrchestratorRestService$1.write(OrchestratorRestService.java:62)
	at org.apache.cxf.jaxrs.provider.BinaryDataProvider.writeTo(BinaryDataProvider.java:172)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.writeMessageBody(JAXRSUtils.java:1381)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.serializeMessage(JAXRSOutInterceptor.java:244)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.processResponse(JAXRSOutInterceptor.java:120)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleMessage(JAXRSOutInterceptor.java:83)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.interceptor.OutgoingChainInterceptor.handleMessage(OutgoingChainInterceptor.java:83)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:253)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:287)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: org.eclipse.egit.github.core.client.RequestException: Not Found (404)
	at org.pentaho.build.buddy.bundles.source.github.GithubSourceRetriever.onStop(GithubSourceRetriever.java:280)
	at org.pentaho.build.buddy.bundles.source.github.SlackbotGithubSourceRetriever.onStop(SlackbotGithubSourceRetriever.java:36)
	at Proxy9d06b07d_ca2a_4133_adf6_83b92691d70e.onStop(Unknown Source)
	at org.pentaho.build.buddy.bundles.orchestrator.OrchestratorImpl.doNotBuild(OrchestratorImpl.java:516)
	at org.pentaho.build.buddy.bundles.orchestrator.OrchestratorImpl.orchestrate(OrchestratorImpl.java:354)
	... 41 more
Caused by: org.eclipse.egit.github.core.client.RequestException: Not Found (404)
	at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:552)
	at org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:643)
	at org.eclipse.egit.github.core.client.GitHubClient.post(GitHubClient.java:757)
	at org.pentaho.build.buddy.bundles.source.github.GithubCommitService$Delegate$1.post(GithubCommitService.java:50)
	at org.eclipse.egit.github.core.service.CommitService.createStatus(CommitService.java:426)
	at org.pentaho.build.buddy.bundles.source.github.GithubCommitService.createStatus(GithubCommitService.java:35)
	at org.pentaho.build.buddy.bundles.source.github.GithubSourceRetriever.onStop(GithubSourceRetriever.java:278)
	... 45 more

```

2017-12-05 11:27 UTC, wingman-pentaho commented
### Build Skipped

:white_check_mark: There was nothing to build. The changes are probably excluded by the build rules. If this is an error, please contact your system administrator.

2017-12-05 11:27 UTC, wingman-pentaho commented
### Build Failed

:x: Something went wrong while validating this pull request.

#### Build Commands

```sh
```

##### Stdout log
###### (last 100 lines)

```console
Config enriched: If no api token specified, use environment variable
Config enriched: If source control is github, set git binary path
Config enriched: Set the slackbot url
Config enriched: If github SourceControlType and null StatusUpdateType, use github
Config enriched: If github SourceControlType and StatusUpdaterType and null ApiToken, use the one from SourceRetriever
Config enriched: If github SourceControlType and StatusUpdaterType and null Organization, use the one from SourceRetriever
Config enriched: If github SourceControlType and StatusUpdaterType and null Repository, use the one from SourceRetriever
Config enriched: If github SourceControlType and StatusUpdaterType and null PullRequest, use the one from SourceRetriever
Config enriched: CheckstyleAnalyzer is enabled by default
Retrieving source with org.pentaho.build.buddy.bundles.source.github.SlackbotGithubSourceRetriever@470a9c72
VCS Commands:
clone: [git, clone, --depth=1, --branch, master, https://[GITHUB TOKEN]@github.com/pentaho/pentaho-engineering-samples.git, pentaho-engineering-samples-base-42-45400ce8-e5c2-4178-bdcc-f986d9e788b2]
fetch: [git, fetch, --depth=4, origin, pull/42/head:pullRequest]
merge: [git, merge, --no-edit, --no-ff, -Xtheirs, -Xignore-space-change, pullRequest]
HEAD is now at 09288b8 Merge pull request #43 from jonjarvis/BISERVER-13491
Merge made by the 'recursive' strategy.
 .../javascript-apis/platform/visual-samples-bar-d3/.npmignore         | 2 +-
 .../javascript-apis/platform/visual-samples-bar-d3/sandbox.html       | 4 ++--
 2 files changed, 3 insertions(+), 3 deletions(-)
GithubSourceRetriever file list:
[modified]	Samples_for_Extending_Pentaho/javascript-apis/platform/visual-samples-bar-d3/.npmignore
[modified]	Samples_for_Extending_Pentaho/javascript-apis/platform/visual-samples-bar-d3/sandbox.html
BuildToolDetector unable to determine build type, falling back to config defaults
Build file exclusion pattern: (\A|/)(assembly|assemblies)/
```

#### Stderr log
###### (last 100 lines)

```console
Cloning into 'pentaho-engineering-samples-base-42-45400ce8-e5c2-4178-bdcc-f986d9e788b2'...
From https://github.com/pentaho/pentaho-engineering-samples
 * [new ref]         refs/pull/42/head -> pullRequest
java.lang.Exception: java.lang.RuntimeException: org.eclipse.egit.github.core.client.RequestException: Not Found (404)
	at org.pentaho.build.buddy.bundles.orchestrator.OrchestratorImpl.orchestrate(OrchestratorImpl.java:387)
	at Proxy9b08e361_324e_4973_bb9a_6779c53c59af.orchestrate(Unknown Source)
	at org.pentaho.build.buddy.bundles.rest.OrchestratorRestService$1.write(OrchestratorRestService.java:62)
	at org.apache.cxf.jaxrs.provider.BinaryDataProvider.writeTo(BinaryDataProvider.java:172)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.writeMessageBody(JAXRSUtils.java:1381)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.serializeMessage(JAXRSOutInterceptor.java:244)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.processResponse(JAXRSOutInterceptor.java:120)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleMessage(JAXRSOutInterceptor.java:83)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.interceptor.OutgoingChainInterceptor.handleMessage(OutgoingChainInterceptor.java:83)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:253)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:287)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: org.eclipse.egit.github.core.client.RequestException: Not Found (404)
	at org.pentaho.build.buddy.bundles.source.github.GithubSourceRetriever.onStop(GithubSourceRetriever.java:280)
	at org.pentaho.build.buddy.bundles.source.github.SlackbotGithubSourceRetriever.onStop(SlackbotGithubSourceRetriever.java:36)
	at Proxyd87598ef_9683_4136_b4e2_3c4b958b7757.onStop(Unknown Source)
	at org.pentaho.build.buddy.bundles.orchestrator.OrchestratorImpl.doNotBuild(OrchestratorImpl.java:516)
	at org.pentaho.build.buddy.bundles.orchestrator.OrchestratorImpl.orchestrate(OrchestratorImpl.java:354)
	... 41 more
Caused by: org.eclipse.egit.github.core.client.RequestException: Not Found (404)
	at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:552)
	at org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:643)
	at org.eclipse.egit.github.core.client.GitHubClient.post(GitHubClient.java:757)
	at org.pentaho.build.buddy.bundles.source.github.GithubCommitService$Delegate$1.post(GithubCommitService.java:50)
	at org.eclipse.egit.github.core.service.CommitService.createStatus(CommitService.java:426)
	at org.pentaho.build.buddy.bundles.source.github.GithubCommitService.createStatus(GithubCommitService.java:35)
	at org.pentaho.build.buddy.bundles.source.github.GithubSourceRetriever.onStop(GithubSourceRetriever.java:278)
	... 45 more

```

2017-12-05 18:01 UTC, wingman-pentaho commented
### Build Skipped

:white_check_mark: There was nothing to build. The changes are probably excluded by the build rules. If this is an error, please contact your system administrator.

2017-12-05 18:01 UTC, wingman-pentaho commented
### Build Failed

:x: Something went wrong while validating this pull request.

#### Build Commands

```sh
```

##### Stdout log
###### (last 100 lines)

```console
Config enriched: If no api token specified, use environment variable
Config enriched: If source control is github, set git binary path
Config enriched: Set the slackbot url
Config enriched: If github SourceControlType and null StatusUpdateType, use github
Config enriched: If github SourceControlType and StatusUpdaterType and null ApiToken, use the one from SourceRetriever
Config enriched: If github SourceControlType and StatusUpdaterType and null Organization, use the one from SourceRetriever
Config enriched: If github SourceControlType and StatusUpdaterType and null Repository, use the one from SourceRetriever
Config enriched: If github SourceControlType and StatusUpdaterType and null PullRequest, use the one from SourceRetriever
Config enriched: CheckstyleAnalyzer is enabled by default
Retrieving source with org.pentaho.build.buddy.bundles.source.github.SlackbotGithubSourceRetriever@4538d805
VCS Commands:
clone: [git, clone, --depth=1, --branch, master, https://[GITHUB TOKEN]@github.com/pentaho/pentaho-engineering-samples.git, pentaho-engineering-samples-base-42-871a40b8-9937-4ba7-a9a1-c35aed970fbc]
fetch: [git, fetch, --depth=4, origin, pull/42/head:pullRequest]
merge: [git, merge, --no-edit, --no-ff, -Xtheirs, -Xignore-space-change, pullRequest]
HEAD is now at 09288b8 Merge pull request #43 from jonjarvis/BISERVER-13491
Merge made by the 'recursive' strategy.
 .../javascript-apis/platform/visual-samples-bar-d3/.npmignore         | 2 +-
 .../javascript-apis/platform/visual-samples-bar-d3/sandbox.html       | 4 ++--
 2 files changed, 3 insertions(+), 3 deletions(-)
GithubSourceRetriever file list:
[modified]	Samples_for_Extending_Pentaho/javascript-apis/platform/visual-samples-bar-d3/.npmignore
[modified]	Samples_for_Extending_Pentaho/javascript-apis/platform/visual-samples-bar-d3/sandbox.html
BuildToolDetector unable to determine build type, falling back to config defaults
Build file exclusion pattern: (\A|/)(assembly|assemblies)/
```

#### Stderr log
###### (last 100 lines)

```console
Cloning into 'pentaho-engineering-samples-base-42-871a40b8-9937-4ba7-a9a1-c35aed970fbc'...
From https://github.com/pentaho/pentaho-engineering-samples
 * [new ref]         refs/pull/42/head -> pullRequest
java.lang.Exception: java.lang.RuntimeException: org.eclipse.egit.github.core.client.RequestException: Not Found (404)
	at org.pentaho.build.buddy.bundles.orchestrator.OrchestratorImpl.orchestrate(OrchestratorImpl.java:387)
	at Proxycc3f1c27_804b_4ddd_bcaa_6596d8e073dd.orchestrate(Unknown Source)
	at org.pentaho.build.buddy.bundles.rest.OrchestratorRestService$1.write(OrchestratorRestService.java:62)
	at org.apache.cxf.jaxrs.provider.BinaryDataProvider.writeTo(BinaryDataProvider.java:172)
	at org.apache.cxf.jaxrs.utils.JAXRSUtils.writeMessageBody(JAXRSUtils.java:1381)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.serializeMessage(JAXRSOutInterceptor.java:244)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.processResponse(JAXRSOutInterceptor.java:120)
	at org.apache.cxf.jaxrs.interceptor.JAXRSOutInterceptor.handleMessage(JAXRSOutInterceptor.java:83)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.interceptor.OutgoingChainInterceptor.handleMessage(OutgoingChainInterceptor.java:83)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:253)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:298)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:217)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:273)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:71)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:287)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: org.eclipse.egit.github.core.client.RequestException: Not Found (404)
	at org.pentaho.build.buddy.bundles.source.github.GithubSourceRetriever.onStop(GithubSourceRetriever.java:280)
	at org.pentaho.build.buddy.bundles.source.github.SlackbotGithubSourceRetriever.onStop(SlackbotGithubSourceRetriever.java:36)
	at Proxy695e3300_ea6f_48fc_bd3b_6075d201ded8.onStop(Unknown Source)
	at org.pentaho.build.buddy.bundles.orchestrator.OrchestratorImpl.doNotBuild(OrchestratorImpl.java:516)
	at org.pentaho.build.buddy.bundles.orchestrator.OrchestratorImpl.orchestrate(OrchestratorImpl.java:354)
	... 41 more
Caused by: org.eclipse.egit.github.core.client.RequestException: Not Found (404)
	at org.eclipse.egit.github.core.client.GitHubClient.createException(GitHubClient.java:552)
	at org.eclipse.egit.github.core.client.GitHubClient.sendJson(GitHubClient.java:643)
	at org.eclipse.egit.github.core.client.GitHubClient.post(GitHubClient.java:757)
	at org.pentaho.build.buddy.bundles.source.github.GithubCommitService$Delegate$1.post(GithubCommitService.java:50)
	at org.eclipse.egit.github.core.service.CommitService.createStatus(CommitService.java:426)
	at org.pentaho.build.buddy.bundles.source.github.GithubCommitService.createStatus(GithubCommitService.java:35)
	at org.pentaho.build.buddy.bundles.source.github.GithubSourceRetriever.onStop(GithubSourceRetriever.java:278)
	... 45 more

```

2017-12-05 18:03 UTC, davidmsantos90 approved these changes

2017-12-12 17:15 UTC, dcleao commented
@pamval you can already merge this, when possible. Thanks!

2017-12-12 22:07 UTC, merged